    @Test(dataProvider = "throwableProvider")
    public void shouldIgnoreExceptionsOnDockerImagePullingIfForcePullIsEnabled(Throwable throwable) throws Throwable {
        final Object[] arguments = {dockerfile, lineConsumer, "string", Boolean.TRUE};
        when(methodInvocation.getArguments()).thenReturn(arguments);
        when(dockerfile.getImages()).thenReturn(Collections.singletonList(dockerImage));
        final String tag = "latest";
        final String repo = "my_repo/my_image";
        when(dockerImage.getFrom()).thenReturn(repo + ":" + tag);
        doThrow(throwable).when(dockerConnector).pull(anyString(), anyString(), anyString(), any(ProgressMonitor.class));


        interceptor.invoke(methodInvocation);


        assertFalse((Boolean)arguments[3]);
        verify(methodInvocation).proceed();
    }

