  @Test
  public void testFail6() throws Exception {
    setFieldsForTest("testfail6");
    projectExplorer.openItemByPath(pathToCurrentPackage + "/A.java");
    editor.waitActive();
    editor.waitTextIntoEditor(contentFromInA);
    editor.setCursorToLine(14);
    editor.typeTextIntoEditor(Keys.END.toString());
    editor.typeTextIntoEditor(Keys.ARROW_LEFT.toString());
    editor.launchRefactorForm();
    refactor.waitRenameFieldFormIsOpen();
    refactor.waitUpdateReferencesIsSelected();
    refactor.typeAndWaitNewName("g");
    refactor.clickOkButtonRefactorForm();
    askDialog.acceptDialogWithText(
        "After renaming, the field 'f' will be hidden"
            + " in the scope of the field 'g' declared in type 'testfail6.A.B'");
    refactor.waitRenameFieldFormIsClosed();
    editor.closeFileByNameWithSaving("A");
  }

