    @Test
	public void testFail72() throws Exception {
		helper1();
	}

