  @Test
  public void test45() throws Exception {
    helper2("A", "B");
  }

