  @Test
  public void resolveTest() throws Exception {
    menu.runCommand(WORKSPACE, IMPORT_PROJECT);
    subversion.waitAndTypeImporterAsSvnInfo(
        svnRepo1UrlProvider.get(),
        PROJECT_NAME,
        svnUsernameProvider.get(),
        svnPasswordProvider.get());
    importProjectFromLocation.waitMainFormIsClosed();

    wizard.waitOpenProjectConfigForm();
    wizard.clickSaveButton();
    wizard.waitCloseProjectConfigForm();

    loader.waitOnClosed();
    projectExplorer.waitItem(PROJECT_NAME);
    projectExplorer.openItemByPath(PROJECT_NAME);

    projectExplorer.openItemByPath(PROJECT_NAME + "/tags");
    projectExplorer.openItemByPath(CONFLICT_FILE);
    editor.typeTextIntoEditor(CONFLICT_CHANGES, 1);
    menu.runCommand(SUBVERSION, SVN_UPDATE_TO_REVISION);
    subversion.waitSvnUpdateToRevisionFormOpened();
    subversion.selectSvnUpdateToRevision();
    subversion.typeSvnUpdateToRevisionName("2");

    subversion.clickSvnUpdateToRevisionButtonUpdate();
    subversion.waitSvnUpdateToRevisionFormClosed();
    resolve(CONFLICT_FILE, "mine-conflict");
    loader.waitOnClosed();
    menu.runCommand(SUBVERSION, SVN_UPDATE_TO_REVISION);
    subversion.waitSvnUpdateToRevisionFormOpened();
    subversion.selectSvnUpdateToRevision();
    subversion.typeSvnUpdateToRevisionName("3");
    subversion.clickSvnUpdateToRevisionButtonUpdate();
    subversion.waitSvnUpdateToRevisionFormClosed();
    resolve(CONFLICT_FILE, "theirs-conflict");
  }

