  @Test
  public void shouldPrintErrorWhenFailedAddToIndex() throws Exception {
    when(constant.addFailed()).thenReturn(MESSAGE);

    presenter.onAddClicked();
    verify(voidPromise).catchError(promiseErrorCaptor.capture());
    promiseErrorCaptor.getValue().apply(null);

    verify(console).printError(eq(MESSAGE));
    verify(notificationManager).notify(eq(MESSAGE), eq(FAIL), eq(FLOAT_MODE));
  }

