    public FunctionException(String message, Throwable cause) {
        super(message, cause);
    }

