    @Test(expectedExceptions = InfrastructureException.class, expectedExceptionsMessageRegExp = "oops")
    public void findsIdentitiesRethrowsIOExceptionThrownWhileListingContainersAsInternalInfraException() throws Exception {
        when(docker.listContainers(anyObject())).thenThrow(new IOException("oops"));

        containers.findIdentities();
    }

