    @Test(expectedExceptions = InfrastructureException.class, expectedExceptionsMessageRegExp = "oops")
    public void findsIdentitiesRethrowsIOExceptionThrownWhileListingContainersAsInternalInfraException() throws Exception {
        when(docker.listContainers(ListContainersParams.create().withAll(false))).thenThrow(new IOException("oops"));

        containers.findIdentities();
    }

