    @Test(dependsOnMethods = "shouldThrowNotFoundExceptionWhenGettingNonExistingRecipe",
          expectedExceptions = NotFoundException.class)
    public void shouldNotCreateRecipeWhenSubscriberThrowsExceptionOnRecipeStoring() throws Exception {
        final RecipeImpl recipe = createRecipe(0);

        CascadeEventSubscriber<RecipePersistedEvent> subscriber = mockCascadeEventSubscriber();
        doThrow(new ConflictException("error")).when(subscriber).onCascadeEvent(any());
        eventService.subscribe(subscriber, RecipePersistedEvent.class);

        try {
            recipeDao.create(recipe);
            fail("RecipeDao#create had to throw conflict exception");
        } catch (ConflictException ignored) {
        }

        eventService.unsubscribe(subscriber, RecipePersistedEvent.class);
        recipeDao.getById(recipe.getId());
    }

